#!/usr/bin/env bash

## Collect data
cache_dir="$HOME/.cache/eww/lock/weather"
cache_data="$cache_dir/data"
cache_description="$cache_dir/description"
cache_temperature="$cache_dir/temperature"
cache_quote="$cache_dir/quote"
cache_hint="$cache_dir/hint"
cache_color="$cache_dir/color"
cache_icon="$cache_dir/icon"

## Make cache dir
if [[ ! -d "$cache_dir" ]]; then
	mkdir -p "$cache_dir"
fi

## Weather data
key="YOUR_API_KEY"
id="YOUR_CITY_ID"
unit="metric" #Options are 'metric' and 'imperial'
openweathermap_url="http://api.openweathermap.org/data/2.5/weather?APPID=$key&id=$id&units=$unit"

# Variables

declare data        # weather data from openweathermap.org
declare description # weather description
declare temperature # weather temperature
declare quote       # weather quote
declare hint        # weather hint
declare color       # weather icon color
declare icon        # weather icon

# Functions

## Generate weather data from openweathermap.org
## If failed, use cached data
generate_data() {
	if data=$(curl -sf "$openweathermap_url"); then
		temperature=$(echo "$data" | jq ".main.temp" | cut -d "." -f 1)"°C"
		description=$(echo "$data" | jq -r ".weather[].description" | head -1 | sed -e "s/\b\(.\)/\u\1/g")

		analyse "$(echo "$data" | jq -r ".weather[].icon" | head -1)"

		store_data_cache
	else
		load_from_cache
	fi
}

## Analyse icon_code and generate icon/color/quote/hint
## $1: icon_code
analyse() {
	case "$1" in
	"50d")
		icon=" "
		color="#84afdb"
		quote="Forecast says it's misty"
		hint="Make sure you don't get lost on your way..."
		;;
	"50n")
		icon=" "
		color="#84afdb"
		quote="Forecast says it's a misty night"
		hint="Don't go anywhere tonight or you might get lost..."
		;;
	"01d")
		icon=" "
		color="#ffd86b"
		quote="It's a sunny day, gonna be fun!"
		hint="Don't go wandering all by yourself though..."
		;;
	"01n")
		icon=" "
		color="#fcdcf6"
		quote="It's a clear night"
		hint="You might want to take a evening stroll to relax..."
		;;
	"02d")
		icon=" "
		color="#adadff"
		quote="It's  cloudy, sort of gloomy"
		hint="You'd better get a book to read..."
		;;
	"02n")
		icon=" "
		color="#adadff"
		quote="It's a cloudy night"
		hint="How about some hot chocolate and a warm bed?"
		;;
	"03d")
		icon=" "
		color="#adadff"
		quote="It's  cloudy, sort of gloomy"
		hint="You'd better get a book to read..."
		;;
	"03n")
		icon=" "
		color="#adadff"
		quote="It's a cloudy night"
		hint="How about some hot chocolate and a warm bed?"
		;;
	"04d")
		icon=" "
		color="#adadff"
		quote="It's  cloudy, sort of gloomy"
		hint="You'd better get a book to read..."
		;;
	"04n")
		icon=" "
		color="#adadff"
		quote="It's a cloudy night"
		hint="How about some hot chocolate and a warm bed?"
		;;
	"09d")
		icon=" "
		color="#6b95ff"
		quote="It's rainy, it's a great day!"
		hint="Get some ramen and watch as the rain falls..."
		;;
	"09n")
		icon=" "
		color="#6b95ff"
		quote=" It's gonna rain tonight it seems"
		hint="Make sure your clothes aren't still outside..."
		;;
	"10d")
		icon=" "
		color="#6b95ff"
		quote="It's rainy, it's a great day!"
		hint="Get some ramen and watch as the rain falls..."
		;;
	"10n")
		icon=" "
		color="#6b95ff"
		quote=" It's gonna rain tonight it seems"
		hint="Make sure your clothes aren't still outside..."
		;;
	"11d")
		icon=""
		color="#ffeb57"
		quote="There's storm for forecast today"
		hint="Make sure you don't get blown away..."
		;;
	"11n")
		icon=""
		color="#ffeb57"
		quote="There's gonna be storms tonight"
		hint="Make sure you're warm in bed and the windows are shut..."
		;;
	"13d")
		icon=" "
		color="#e3e6fc"
		quote="It's gonna snow today"
		hint="You'd better wear thick clothes and make a snowman as well!"
		;;
	"13n")
		icon=" "
		color="#e3e6fc"
		quote="It's gonna snow tonight"
		hint="Make sure you get up early tomorrow to see the sights..."
		;;
	"40d")
		icon=" "
		color="#84afdb"
		quote="Forecast says it's misty"
		hint="Make sure you don't get lost on your way..."
		;;
	"40n")
		icon=" "
		color="#84afdb"
		quote="Forecast says it's a misty night"
		hint="Don't go anywhere tonight or you might get lost..."
		;;
	*)
		icon=" "
		color="#adadff"
		quote="Sort of odd, I don't know what to forecast"
		hint="Make sure you have a good time!"
		;;
	esac
}

## Store weather data in cache
store_data_cache() {
	echo "$data" >"$cache_data"
	echo "$icon" >"$cache_icon"
	echo "$description" >"$cache_description"
	echo "$temperature" >"$cache_temperature"
	echo "$quote" >"$cache_quote"
	echo "$color" >"$cache_color"
	echo "$hint" >"$cache_hint"
}

## Load weather data from cache
load_from_cache() {
	data=$(cat "$cache_data")
	icon=$(cat "$cache_icon")
	description=$(cat "$cache_description")
	temperature=$(cat "$cache_temperature")
	quote=$(cat "$cache_quote")
	color=$(cat "$cache_color")
	hint=$(cat "$cache_hint")
}

## Print weather data
## $1: weather data
print_data() {
	echo "$data" | jq .
	echo "Icon:         $icon"
	echo "Color:        $color"
	echo "Temperature:  $temperature"
	echo "Description:  $description"
	echo "Quote:        $quote"
	echo "Hint:         $hint"
}

## Print help message
print_help() {
	echo "Usage: $0 [OPTION]"
	echo "Options:"
	echo "  --help          Print this help message"
	echo "  --data          Print all weather data"
	echo "  --icon          Print weather icon"
	echo "  --color         Print weather icon color"
	echo "  --temperature   Print temperature"
	echo "  --description   Print weather description"
	echo "  --quote         Print quote"
	echo "  --hint          Print hint"
}

# Execution
case "$1" in
"--data")
	generate_data
	print_data
	;;
"--icon")
	generate_data
	echo "$icon"
	;;
"--color")
	generate_data
	echo "$color"
	;;
"--temperature")
	generate_data
	echo "$temperature"
	;;
"--description")
	generate_data
	echo "$description"
	;;
"--quote")
	generate_data
	echo "$quote"
	;;
"--hint")
	generate_data
	echo "$hint"
	;;
*)
	print_help
	;;
esac
